### ISSUE TITLE
make llvm during last steps of build, llvm-backend compilation error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cwalls251/iphone-dev#82]
```
What steps will reproduce the problem?
1. build toolchain
2. make LLVM_VERSION_INFO=2.0-svn-iphone-dev-0.3-svn

What is the expected output? What do you see instead?
clean compile.

In file included from /opt/local/lib/llvm/src/include/llvm/ADT/SmallPtrSet.h:20,
                 from /opt/local/lib/llvm/src/include/llvm/ADT/SmallSet.h:18,
                 from /opt/local/lib/llvm/src/include/llvm/ADT/SetVector.h:23,
                 from ../../../llvm-gcc-4.0-iphone/gcc/llvm-internal.h:37,
                 from ../../../llvm-gcc-4.0-iphone/gcc/llvm-backend.cpp:23:
/opt/local/lib/llvm/obj/include/llvm/Support/DataTypes.h:38:3: error: #error 
"Must #define 
__STDC_LIMIT_MACROS before #including Support/DataTypes.h"
../../../llvm-gcc-4.0-iphone/gcc/llvm-backend.cpp: In function 'void 
createOptimizationPasses()':
/opt/local/lib/llvm/src/include/llvm/Transforms/Scalar.h:130: error: too many 
arguments to 
function 'llvm::LoopPass* llvm::createLoopUnswitchPass()'
../../../llvm-gcc-4.0-iphone/gcc/llvm-backend.cpp:342: error: at this point in 
file
../../../llvm-gcc-4.0-iphone/gcc/llvm-backend.cpp:348: error: 'createGVNPass' 
was not 
declared in this scope
make[1]: *** [llvm-backend.o] Error 1
make: *** [all-gcc] Error 2



```

Original issue reported on code.google.com by `gelli...@gmail.com` on 16 Oct 2007 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
just tried a clean build using revision 42498.  still getting same error.

In file included from /opt/local/lib/llvm/src/include/llvm/ADT/SmallPtrSet.h:20,
                 from /opt/local/lib/llvm/src/include/llvm/ADT/SmallSet.h:18,
                 from /opt/local/lib/llvm/src/include/llvm/ADT/SetVector.h:23,
                 from ../../../llvm-gcc-4.0-iphone/gcc/llvm-internal.h:37,
                 from ../../../llvm-gcc-4.0-iphone/gcc/llvm-backend.cpp:23:
/opt/local/lib/llvm/obj/include/llvm/Support/DataTypes.h:38:3: error: #error 
"Must #define 
__STDC_LIMIT_MACROS before #including Support/DataTypes.h"
../../../llvm-gcc-4.0-iphone/gcc/llvm-backend.cpp: In function 'void 
createOptimizationPasses()':
/opt/local/lib/llvm/src/include/llvm/Transforms/Scalar.h:130: error: too many 
arguments to function 
'llvm::LoopPass* llvm::createLoopUnswitchPass()'
../../../llvm-gcc-4.0-iphone/gcc/llvm-backend.cpp:342: error: at this point in 
file
../../../llvm-gcc-4.0-iphone/gcc/llvm-backend.cpp:348: error: 'createGVNPass' 
was not declared in this 
scope
make[1]: *** [llvm-backend.o] Error 1
make: *** [all-gcc] Error 2
llvm-gcc-4.0-iphone > 

```

Original comment by `gelli...@gmail.com` on 18 Oct 2007 at 8:40

**Comment by GoogleCodeExporter** [comment]
```
Having the same problem.  Would really like to hear from someone who knows how 
to fix
this.
```

Original comment by `vaum...@gmail.com` on 21 Oct 2007 at 8:06

**Comment by GoogleCodeExporter** [comment]
```
I have this exact same problem on Leopard and Intel only.
I'm using 42498 as well.
```

Original comment by `arf...@gmail.com` on 18 Nov 2007 at 7:46

**Comment by GoogleCodeExporter** [comment]
```
I have same issue on OS X 10.4.11
```

Original comment by `HardyMa...@gmail.com` on 27 Dec 2007 at 5:51

**Comment by GoogleCodeExporter** [comment]
```
Have the same problem. Clean build on 10.5.2/Intel
```

Original comment by `p0p...@gmail.com` on 27 Feb 2008 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
Stilling having issue on 10.5.2/Intel.
```

Original comment by `HardyMa...@gmail.com` on 14 Mar 2008 at 3:24
